#conda env update --file environment.yml --prune
# sudo apt install cuda=11.6.2-1
name: f3
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - ipykernel
  - ipywidgets
  - jupyterlab_widgets
  - python<3.10
  - pip
  - tqdm
  - psycopg2
  - SQLAlchemy
  - pandas
  - Pillow
  - voila
  - fastapi
  - uvicorn
  - pip:
    - --find-links https://download.pytorch.org/whl/torch_stable.html
    - torch==1.12.1+cu116
    - torchvision==0.13.1+cu116
    - transformers
    - tendo
    - dateparser
    - matplotlib
    - plotly
    - ftfy
    - schedule
    - psutil
    - docker
    - wrapt
    - nbdev
    - aiogram
    - qdrant_client
    - tzwhere
    - terminaltables